budgets/urls.py
from django.urls import path

from . import views

app_name = 'budgets'
urlpatterns = [
    path('', views.BudgetListView.as_view(), name='budget'),
]

control/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('acceder/', include('users.urls')),
    path('', include('budgets.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT,
    )

users/urls.py
from django.urls import path

from . import views

app_name = 'users'
urlpatterns = [
    path('', views.login_view, name='login'),
    path('cerrar_sesion/', views.logout_view, name='logout'),
    path('registrarse/', views.register, name='register'),
]

budgets/models.py
from django.db import models

from users.models import User


class Budget(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    quantity = models.DecimalField(max_digits=10, decimal_places=3)
    spending = models.DecimalField(
        max_digits=10, decimal_places=3, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username

profiles/models.py
from PIL import Image
from django.db import models
from django.dispatch import receiver
from django.utils.text import slugify
from django.db.models.signals import post_save, pre_save

from users.models import User


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.CharField(max_length=14, null=True, blank=True)
    direction = models.CharField(max_length=80, null=True, blank=True)
    image = models.ImageField(default='avatar.png', upload_to='profiles/')
    slug = models.SlugField(max_length=50, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username


@receiver(post_save, sender=User)
def set_profile_user(sender, instance, *args, **kwargs):
    if kwargs.get('created', False):
        Profile.objects.create(user=instance)


@receiver(post_save, sender=Profile)
def set_image(sender, instance, *args, **kwargs):
    img = Image.open(instance.image.path)
    if img.height > 400 and img.width > 400:
        size = (400, 400)
        img.thumbnail(size)
        img.save(instance.image.path)


@receiver(pre_save, sender=Profile)
def set_slug_profile(sender, instance, *args, **kwargs):
    if instance.user.username:
        instance.slug = slugify(instance.user.username)

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    def __str__(self):
        return self.username

budgets/forms.py
from django.forms import ModelForm

from .models import Budget


class BudgetForm(ModelForm):
    class Meta:
        model = Budget
        fields = (
            'quantity', 'spending'
        )

users/forms.py
from django.contrib.auth.forms import UserCreationForm

from .models import User


class UserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({
            'class': 'form-control',
        })
        self.fields['email'].widget.attrs.update({
            'class': 'form-control',
        })
        self.fields['password1'].widget.attrs.update({
            'class': 'form-control',
        })
        self.fields['password2'].widget.attrs.update({
            'class': 'form-control',
        })

budgets/views.py
from django.shortcuts import render
from django.views.generic import ListView

from .models import Budget
from .forms import BudgetForm


class BudgetListView(ListView):
    template_name = 'budgets/budget.html'
    queryset = Budget.objects.all().order_by('-pk')

profiles/views.py
from django.shortcuts import render

# Create your views here.

users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import login, logout, authenticate

from .forms import UserForm


def login_view(request):
    template_name = 'users/login.html'

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            login(request, user)
            messages.success(request, f'Bienvenido {user.username}')
            return redirect('budgets:budget')
        else:
            messages.error(request, 'Usuario o Contraseña invalidos')

    return render(request, template_name)


def logout_view(request):
    logout(request)
    messages.success(request, 'Sesion cerrada exitosamente')
    return redirect('users:login')


def register(request):
    template_name = 'users/register.html'
    form = UserForm(request.POST)

    if request.method == 'POST' and form.is_valid():
        user = form.save()
        if user:
            login(request, user)
            messages.success(
                request, f'El usuario {user.username} ha sido creado exitosamente'
            )
            return redirect('budgets:budget')

    return render(request, template_name, {
        'form': form,
    })

budgets/templates/budgets/budget.html
{% extends 'base.html' %}
{% block content %}
    <div class="card h-100 mt-2">
        <div class="card-body">
            {% if object_list %}
                <h4 class="card-text text-center">Mi presupuesto</h4>
                <p class="card-text">Cantidad: {{ object_list.quantity }}</p>
                <p class="card-text">Ultimo gasto: {{ object_list.spending }}</p>
            {% else %}
                <p class="card-text">No cuenta con un presupuesto <a href="#">Click para hacer uno</a></p>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Control</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css"
        integrity="sha384-r4NyP46KrjDleawBgD5tp8Y7UzmLA05oM1iAEQ17CSuDqnUK2+k9luXQOfXJCJ4I" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/ddd46d4aa2.js" crossorigin="anonymous"></script>
</head>

<body>
    {% include 'navbar.html' %}
    {% include 'messages.html' %}
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.min.js"
        integrity="sha384-oesi62hOLfzrys4LxRF63OJCXdXDipiYWBnvTl9Y9/TRlw5xlKIEHpNyvvDShgf/"
        crossorigin="anonymous"></script>
</body>

</html>

templates/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert {% if message.tags == 'success' %}alert-success{% else %}alert-warning{% endif %} alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endfor %}
{% endif %}

templates/navbar.html
{% url 'users:login' as login %}
{% url 'users:logout' as logout %}
{% url 'users:register' as register %}
{% url 'budgets:budget' as badget %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto mb-2 mb-lg-0">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == badget %}active{% endif %}" href="{{ badget }}">
                            <span><i class="fas fa-coins"></i></span>
                            Presupuesto
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == logout %}active{% endif %}" href="{{ logout }}">
                            <span><i class="fas fa-sign-out-alt"></i></span>
                            Cerrar Sesion
                        </a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == login %}active{% endif %}" href="{{ login }}">
                            <span><i class="fas fa-sign-in-alt"></i></span>
                            Iniciar Sesion
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == register %}active{% endif %}" href="{{ register }}">
                            <span><i class="fas fa-user-plus"></i></span>
                            Registrarse
                        </a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

templates/users/login.html
{% extends 'base.html' %}
{% block content %}
    <div class="card h-100 text-center mt-2">
        <div class="card-body">
            <div class="row">
                <div class="col-sm-12 col-md-4">
                    <h2 class="card-title">Control</h2>
                    <p class="card-text">
                        Control es un aplicativo web el cual permite el control sobre todos tus procesos en la pandemia
                    </p>
                    <h4 class="card-tite">¿Todavia no tienes una cuenta?</h4>
                    <a href="{% url 'users:register' %}" class="btn btn-danger">¡Crea una ahora!</a>
                </div>
                <div class="col-sm-12 col-md-8">
                    <h3 class="card-title">Iniciar Sesion</h3>
                    <form method="POST">
                        {% csrf_token %}
                        <div class="mb-3">
                            <input type="text" name="username" placeholder="Nombre de Usuario" class="form-control">
                        </div>
                        <div class="mb-3">
                            <input type="password" name="password" placeholder="Contraseña" class="form-control">
                        </div>
                        <button type="submit" class="btn btn-success">Acceder</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/users/register.html
{% extends 'base.html' %}
{% block content %}
    <div class="card h-100 text-center mt-2">
        <div class="card-body">
            <div class="row">
                <div class="col-sm-12 col-md-4">
                    <h2 class="card-title">Control</h2>
                    <p class="card-text">
                        Control es un aplicativo web el cual permite el control sobre todos tus procesos en la pandemia
                    </p>
                    <h4 class="card-tite">¿Ya cuentas con una cuenta?</h4>
                    <a href="{% url 'users:login' %}" class="btn btn-warning">¡Acceder ahora!</a>
                </div>
                <div class="col-sm-12 col-md-8">
                    <h3 class="card-title">Iniciar Sesion</h3>
                    <form method="POST">
                        {% csrf_token %}
                        <div class="mb-3">
                            {% for field in form %}
                                {{ field.label_tag }}
                                {{ field }}
                            {% endfor %}
                        </div>
                        <button type="submit" class="btn btn-primary">Registrarse</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}